"""schema inicial

Revision ID: 2bfa01608aad
Revises: 
Create Date: 2026-05-31 23:52:51.445233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bfa01608aad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comisiones_afp',
    sa.Column('afp', sa.String(), nullable=False),
    sa.Column('comision', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('actualizado_en', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('afp')
    )
    op.create_table('cuotas_historicas',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('afp', sa.String(), nullable=False),
    sa.Column('fondo', sa.String(length=1), nullable=False),
    sa.Column('valor_cuota', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('fecha', 'afp', 'fondo')
    )
    op.create_index('idx_cuotas_afp_fondo_fecha', 'cuotas_historicas', ['afp', 'fondo', 'fecha'], unique=False)
    op.create_table('simulaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('sueldo', sa.Integer(), nullable=False),
    sa.Column('afp', sa.String(), nullable=False),
    sa.Column('fondo', sa.String(length=1), nullable=False),
    sa.Column('saldo_estimado', sa.Integer(), nullable=False),
    sa.Column('pension_mensual', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulaciones')
    op.drop_index('idx_cuotas_afp_fondo_fecha', table_name='cuotas_historicas')
    op.drop_table('cuotas_historicas')
    op.drop_table('comisiones_afp')
    # ### end Alembic commands ###
